Week 2 Discussion
snkirov/objC-card-games pull request #1
Opened 2022-08-23 09:54 UTC by snkirov

2022-08-30 13:26 UTC, cameron-lightricks reviewed
First round of review 😄 please leave any new changes you make in separate new commits so I can see what has changed. Looks great tho!

2022-08-30 13:26 UTC, cameron-lightricks commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +      } else {
As discussed, maybe extract this method to create a random deck of `n` cards to a separate method or initialiser.

2022-08-30 13:26 UTC, cameron-lightricks commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +//  NSLog(@"We chose card %@", card.contents);
Also a candidate for `DebugLog`

2022-08-30 13:26 UTC, cameron-lightricks commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +  }
It seems like this functionality would only result in expected behaviour for the two match game. Considering it's possible to instantiate a game with 3+ matches required, would it be possible to make this code generic somehow?

2022-08-30 13:26 UTC, cameron-lightricks commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +  _lastMoveDescription = [NSMutableString stringWithString:card.contents];
Again, does this only work with a two match game?

2022-08-30 13:26 UTC, cameron-lightricks commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +  long extraCardsRequiredForMatch = _matchCount - 1;
Do you need the `extraCardsRequiredForMatch` state here? It could be replaced by just counting the number of cards in `chosenCards` and comparing to `self.matchCount`. One less piece of state to manage 😄

2022-08-30 14:03 UTC, snkirov commented on ObjectiveCTesting/CardViewController.h
> +@interface CardViewController : UIViewController
I am familiar with the concept. DocC even allows developers to then generate their own Apple-like documentation from the `///` comments. For the sake of time, I will do it in the project for next week and leave it "comment-less" for this PR.

2022-08-30 14:06 UTC, snkirov commented on ObjectiveCTesting/CardViewController.m
> +  _game = [[CardMatchingGame alloc] initWithCardCount: _cards.count usingDeck: playingDeck withMatchCount: MATCH_COUNT];
Cards is a bad name for an outlet collection of 16 buttons from the storyboard. I just didn't want to control drag 16 times again in order to rename it, sorry :)

2022-08-30 14:10 UTC, snkirov commented on ObjectiveCTesting/CardViewController.m
> +//  NSLog(@"Choose at index: %ld", chosenButtonIndex);
I overlooked it. I have some minor experience with the preprocessor, however will experiment a bit with the logging macro you should.

2022-08-30 14:12 UTC, snkirov commented on ObjectiveCTesting/CardViewController.m
> +    [cardButton setBackgroundImage: [self backgroundImageForCard: card] forState:UIControlStateNormal];
I am following the no space approach after our discussion. Again won't waste time here, will just fix it in the next PR.

2022-08-30 14:13 UTC, snkirov commented on ObjectiveCTesting/Model/Card.h
> +- (int)match:(NSArray *)otherCards;
will do in the next PR

2022-08-30 14:13 UTC, snkirov commented on ObjectiveCTesting/Model/CardMatchingGame.h
> +@property (nonatomic, readonly) NSMutableString * lastMoveDescription;
same here

2022-08-30 14:19 UTC, snkirov commented on ObjectiveCTesting/Model/CardMatchingGame.h
> +@property (nonatomic, readonly) NSMutableString * lastMoveDescription;
nice catch, not really necessary, refactored.

2022-08-30 14:20 UTC, snkirov commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +  }
The functionality is working fine, the thing is that on a single turn, always only one card is clicked, thus this is working as it should.

2022-08-30 14:21 UTC, snkirov commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +  _lastMoveDescription = [NSMutableString stringWithString:card.contents];
Nope, it works with a three match game. You can test this by running the Set Game.

2022-08-30 14:28 UTC, snkirov commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +  long extraCardsRequiredForMatch = _matchCount - 1;
Nope, nice catch again. Fixed

2022-08-30 14:30 UTC, snkirov commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +@property (nonatomic, strong) NSMutableArray<Card *> *cards;
Will integrate this change in the new PR to avoid redundancy.

2022-08-30 14:48 UTC, snkirov commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +      } else {
For this PR I moved away from the whole deck logic and am instead using just an array of cards. On the next PR I will try the other approach with the `Deck` data structure.

2022-08-30 14:51 UTC, snkirov commented on ObjectiveCTesting/CardViewController.m
> +    Card *card = [self.game cardAtIndex:cardButtonIndex];
done

2022-08-30 14:54 UTC, snkirov commented on ObjectiveCTesting/CardViewController.m
> +    cardButton.enabled = !card.isMatched;
Isn't this already the case here. The button and the card are very intertwined and I cannot think of a reasonable way to do this. I would be happy if you could elaborate on what could be extracted here.

2022-08-30 15:01 UTC, cameron-lightricks commented on ObjectiveCTesting/CardViewController.m
> +    cardButton.enabled = !card.isMatched;
I just mean that these two lines could be a method returning `Card`:
```
    unsigned long cardButtonIndex = [self.cards indexOfObject:cardButton];
    Card *card = [self.game cardAtIndex:cardButtonIndex];
```
And these 3 lines could be a method taking cardButton and card as parameters:
```
    [cardButton setTitle: [self titleForCard: card] forState: UIControlStateNormal];
    [cardButton setBackgroundImage: [self backgroundImageForCard: card] forState:UIControlStateNormal];
    cardButton.enabled = !card.isMatched;
```
Seperates the logic up into smaller, more understandable chunks

2022-08-30 15:08 UTC, snkirov commented on ObjectiveCTesting/CardViewController.m
> +    cardButton.enabled = !card.isMatched;
thanks for the explanation, nice. Refactored.

2022-08-31 18:47 UTC, cameron-lightricks reviewed
Here's some more comments :)

2022-09-01 08:45 UTC, snkirov commented on ObjectiveCTesting/History/HistoryViewController.h
> +@property (nonatomic, strong) NSString *history;
It could be, definitely.

2022-09-01 08:47 UTC, snkirov commented on .gitignore
> +# Xcode
No, I took it from a previous project of mine. I tend to use it for similar smaller projects

2022-09-01 08:51 UTC, snkirov commented on ObjectiveCTesting/CardViewController.m
> +    }
True, nice catch.

2022-09-01 08:53 UTC, snkirov commented on ObjectiveCTesting/Model/CardMatchingGame.mm
> +    int pointsForThisRound = matchScore * 4;
I should've extracted it in a separate variable. The 4 was referred in the course as a `Match Multiplier Bonus`. Extracted it now.

2022-09-01 08:56 UTC, snkirov commented on ObjectiveCTesting/Model/Deck.m
> +}
True, I usually try to follow this approach. This was left-over from the original course code, fixed it.

2022-09-01 08:56 UTC, snkirov commented on ObjectiveCTesting/Model/Deck.m
> +
Fixed

2022-09-01 08:57 UTC, snkirov commented on ObjectiveCTesting/Model/Deck.m
> +
done

2022-09-01 09:25 UTC, snkirov commented on ObjectiveCTesting/Base.lproj/Main.storyboard
> +                        <color key="backgroundColor" systemColor="systemGray3Color"/>
yup, yup, yup.

2022-09-01 09:51 UTC, snkirov commented on ObjectiveCTesting/CardViewController.m
> +  _history = [[NSMutableString alloc] init];
Definitely a better approach. Since this functionality is no longer required in the next iteration, I wouldn't go over refactoring it right now, but will definitely keep in mind the approach.

2022-09-01 10:04 UTC, snkirov commented on ObjectiveCTesting/Model/PlayingCardDeck.mm
> +  return self;
It is a factory method to create a deck. Refactored it.

2022-09-01 10:08 UTC, snkirov commented on ObjectiveCTesting/Model/PlayingCard.mm
> +}
This makes a ton of sense and is the exact approach which I followed for the SetCard class. I will make sure that the PlayingCard is up to speed in the next PR as well.

2022-09-12 16:09 UTC, cameron-lightricks requested changes
Finally some more comments! I have made comments that I realised you already fixed in later commits, so just mark these as resolved where that has happened! Good work, just some more cleaning up to do. I also couldn't work out what was happening with the merges in the commit history. How come you needed to merge code, and what code was merged?

2022-09-12 16:09 UTC, cameron-lightricks commented on ObjectiveCTesting/Game/CardMatchingGame.mm
> +  return _lastMoveDescriptionMutable;
Maybe use `[self.lastMoveDescriptionMutable copy]` to actually make this an immutable string

2022-09-16 10:01 UTC, snkirov commented
Thanks for the feedback I will collect it all and integrate it in the next PR, in order to avoid writing the same code twice.

2022-09-16 10:01 UTC, snkirov commented on ObjectiveCTesting/CardGame/CardGameViewController.m
> +}
done(next PR)

2022-09-16 10:02 UTC, snkirov commented on ObjectiveCTesting/CardGame/CardGameViewController.m
>    for (UIButton *cardButton in self.cards) {
done(next PR)

2022-09-16 10:10 UTC, snkirov commented on ObjectiveCTesting/CardGame/CardGameViewController.m
> +  [cardButton setBackgroundImage: [self backgroundImageForCard: card] forState:UIControlStateNormal];
done(next PR)

2022-09-16 10:11 UTC, snkirov commented on ObjectiveCTesting/Model/SetModels/SetCard.h
> ++ (NSArray<UIColor *> *)validStrokes;
will be added in the next PR

2022-09-16 10:15 UTC, snkirov commented on ObjectiveCTesting/Model/SetModels/SetCard.h
> ++ (NSArray<UIColor *> *)validStrokes;
I am not sure if you could declare static properties in Objective C. The solution which I can think of right now, would be to change the underlying logic of the methods with static properties which are then returned, but this won't change the interface.

2022-09-16 10:28 UTC, snkirov commented on ObjectiveCTesting/Model/SetModels/SetCard.mm
> +      self = nil;
done (next PR)

2022-09-16 10:28 UTC, snkirov commented on ObjectiveCTesting/Model/SetModels/SetCardDeck.mm
> +  return self;
done (next PR)

2022-09-16 10:32 UTC, snkirov commented on ObjectiveCTesting/Model/SetModels/SetCard.mm
> +}
done (next PR)

2022-09-16 10:33 UTC, snkirov commented on ObjectiveCTesting/Model/SetModels/SetCard.mm
> +}
The property is useless for the SetCard, which is why I will be moving it to the PlayingCard

2022-09-16 10:50 UTC, snkirov commented on ObjectiveCTesting/Modules/SetCardGameModule/ViewController/SetCardGameViewController.mm
> +  } else {
done (next PR)

2022-09-16 10:52 UTC, snkirov commented on ObjectiveCTesting/Modules/BaseGameModule/ViewController/CardGameViewController.h
> +- (NSUInteger)cardsRequiredForMatch; // 2 by default
done (next PR)

2022-09-16 10:53 UTC, snkirov commented on ObjectiveCTesting/Modules/SetCardGameModule/Models/SetCard.mm
> +- (int)match:(NSArray *)otherCards {
will be done in the next pr

2022-09-16 10:54 UTC, snkirov commented on ObjectiveCTesting/Game/CardMatchingGame.mm
> +  _lastMoveDescription = [[NSMutableAttributedString alloc] initWithAttributedString:[card.attributedContents copy]];
Yup, it could and it should. I guess I was just struggling with the obj-c methods :D

2022-09-16 10:54 UTC, snkirov commented on ObjectiveCTesting/Game/CardMatchingGame.mm
> +      auto attributedString = (NSAttributedString *)otherCard.attributedContents;
same story here.

2022-09-16 10:55 UTC, snkirov commented on ObjectiveCTesting/Game/CardMatchingGame.mm
> +    [_lastMoveDescription appendAttributedString: [[NSMutableAttributedString alloc] initWithString:[NSString stringWithFormat:@" matched for %d points.", pointsForThisRound]]];
just NSAttributed should work as well.

2022-09-16 10:55 UTC, snkirov commented on ObjectiveCTesting/Modules/BaseGameModule/Models/Card.h
> +@property (readonly, nonatomic) NSMutableAttributedString *attributedContents;
makes perfect sense.

2022-09-16 10:56 UTC, snkirov commented on ObjectiveCTesting/Modules/BaseGameModule/ViewController/CardGameViewController.m
> +  if (_game.lastMoveDescription && ![_game.lastMoveDescription isEqualToAttributedString: [[NSMutableAttributedString alloc] initWithString:@""]]) {
yup

2022-09-16 10:56 UTC, snkirov commented on ObjectiveCTesting/Modules/History Module/HistoryViewController.h
> +- (void)setupWithAttributedHistory:(NSMutableAttributedString *)attributedHistory;
yup

2022-09-16 10:58 UTC, snkirov commented on ObjectiveCTesting/Modules/BaseGameModule/ViewController/CardGameViewController.h
> -- (NSUInteger)cardsRequiredForMatch; // 2 by default
Makes perfect sense, done in the next PR.

2022-09-16 11:00 UTC, snkirov commented on ObjectiveCTesting/Modules/SetCardGameModule/ViewController/SetCardGameViewController.mm
> +// Overwrites
Completely forgot about it. Fixed in the next PR. 
I prefer using `// MARK: - ` which under the hood I would guess is the same as `#pragma mark -`, since it has the same behaviour.

2022-09-16 11:00 UTC, snkirov commented on ObjectiveCTesting/Modules/SetCardGameModule/Models/SetCard.mm
>  }
yup, yup

2022-09-16 11:01 UTC, snkirov commented on ObjectiveCTesting/Modules/BaseGameModule/Models/Deck.m
> +
just did a ctrl+i on the whole file.

2022-09-16 11:03 UTC, snkirov commented on ObjectiveCTesting/Game/CardMatchingGame.mm
> +  return _lastMoveDescriptionMutable;
sure

2022-09-16 12:55 UTC, snkirov commented on ObjectiveCTesting/Model/SetModels/SetCard.mm
> +                                          NSStrokeWidthAttributeName : @-5 } range: range];
done

2022-09-16 12:57 UTC, snkirov commented on ObjectiveCTesting/Modules/History Module/HistoryViewController.mm
>    if ([_attributedHistory.string isEqualToString:@""]) {
done

2022-09-16 13:01 UTC, snkirov commented on ObjectiveCTesting/Modules/BaseGameModule/ViewController/CardGameViewController.h
> +- (void)updateTitleOfButton:(UIButton *)cardButton forCard:(Card *)card; // has Default Implementation
done (next pr)

2022-09-16 13:15 UTC, snkirov commented on ObjectiveCTesting/Modules/History Module/HistoryViewController.mm
> +  [_attributedHistory addAttributes:attributes range:range];
done

2022-09-20 07:43 UTC, cameron-lightricks commented on ObjectiveCTesting/Model/SetModels/SetCard.h
> ++ (NSArray<UIColor *> *)validStrokes;
You can declare class properties like so: https://useyourloaf.com/blog/objective-c-class-properties/. The implementation of the getter would basically be the same, it would just change the external interface of the data in the header file. Up to you!

2022-09-20 09:49 UTC, snkirov commented on ObjectiveCTesting/Model/SetModels/SetCard.h
> ++ (NSArray<UIColor *> *)validStrokes;
Fixed in the next PR

2022-09-20 09:50 UTC, merged